### PR TITLE
Gps recording service 

### PR DESCRIPTION
**Pull request by glepore98**
-User can view the actual path that was taken during their workout at the of Workout Activity

-> Please test to make sure the points retrieved are always accurate relative to the route that as traveled

### CODE REVIEW

**Comment by glepore98** [comment]
As of now the user only sees a raw poly line on the map with no other data. Feel free to suggest what route info I can add to the view

**Review by ArthurMoreDonuts — COMMENTED** [review]
For some reasons, both recorded workouts and mock data workouts crash the app when opened.

I cannot access the workout activity

**Comment by DLabbate** [comment]
@glepore98 I also cannot access the workout activity.

Steps:
- Record Workout
- Select the recorded workout in the log fragment

Log:

Output
com.google.maps.api.android.lib6.common.apiexception.c: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
        at com.google.maps.api.android.lib6.common.m.b(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):6)
        at com.google.maps.api.android.lib6.gmm6.api.c.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):36)
        at com.google.maps.api.android.lib6.impl.y.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):0)
        at com.google.maps.api.android.lib6.gmm6.api.c.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):47)
        at com.google.maps.api.android.lib6.impl.bi.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):253)
        at com.google.android.gms.maps.internal.i.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):159)
        at ch.onTransact(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):4)
        at android.os.Binder.transact(Binder.java:675)
        at com.google.android.gms.internal.maps.zza.transactAndReadExceptionReturnVoid(Unknown Source:7)
        at com.google.android.gms.maps.internal.zzg.animateCameraWithDurationAndCallback(Unknown Source:14)
        at com.google.android.gms.maps.GoogleMap.animateCamera(Unknown Source:16)
        at com.example.bikebuddy.WorkoutActivity.focusCamera(WorkoutActivity.java:462)
        at com.example.bikebuddy.WorkoutActivity.addPolylineToMap(WorkoutActivity.java:444)
        at com.example.bikebuddy.WorkoutActivity.onMapReady(WorkoutActivity.java:419)
        at com.google.android.gms.maps.zzac.zza(Unknown Source:7)
        at com.google.android.gms.maps.internal.zzaq.dispatchTransaction(Unknown Source:31)
        at com.google.android.gms.internal.maps.zzb.onTransact(Unknown Source:22)
        at android.os.Binder.transact(Binder.java:675)
        at cg.b(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):2)
        at com.google.maps.api.android.lib6.impl.be.run(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2020-04-03 12:16:39.100 18801-18801/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-04-03 12:16:39.102 18801-18801/? E/Zygote: accessInfo : 1

**Comment by DLabbate** [comment]
Process: com.example.bikebuddy, PID: 19656
    com.google.maps.api.android.lib6.common.apiexception.c: Error using newLatLngBounds(LatLngBounds, int): View size is too small after padding is applied.
        at com.google.maps.api.android.lib6.common.m.b(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):6)
        at com.google.maps.api.android.lib6.gmm6.api.c.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):37)
        at com.google.maps.api.android.lib6.impl.y.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):0)
        at com.google.maps.api.android.lib6.gmm6.api.c.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):47)
        at com.google.maps.api.android.lib6.impl.bi.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):253)
        at com.google.android.gms.maps.internal.i.a(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):159)
        at ch.onTransact(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):4)
        at android.os.Binder.transact(Binder.java:675)
        at com.google.android.gms.internal.maps.zza.transactAndReadExceptionReturnVoid(Unknown Source:7)
        at com.google.android.gms.maps.internal.zzg.animateCameraWithDurationAndCallback(Unknown Source:14)
        at com.google.android.gms.maps.GoogleMap.animateCamera(Unknown Source:16)
        at com.example.bikebuddy.WorkoutActivity.focusCamera(WorkoutActivity.java:462)
        at com.example.bikebuddy.WorkoutActivity.addPolylineToMap(WorkoutActivity.java:444)
        at com.example.bikebuddy.WorkoutActivity.onMapReady(WorkoutActivity.java:419)
        at com.google.android.gms.maps.zzac.zza(Unknown Source:7)
        at com.google.android.gms.maps.internal.zzaq.dispatchTransaction(Unknown Source:31)
        at com.google.android.gms.internal.maps.zzb.onTransact(Unknown Source:22)
        at android.os.Binder.transact(Binder.java:675)
        at cg.b(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):2)
        at com.google.maps.api.android.lib6.impl.be.run(:com.google.android.gms.dynamite_mapsdynamite@200914065@20.09.14 (100400-0):2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
2020-04-03 12:17:49.349 1434-3465/? E/KioskModeService: There's no matched data

**Comment by glepore98** [comment]
Its strange that its crashing for you guys. It works fine on my phone. I will look into the error in the log you're getting

**Review by BDeslippe23 — APPROVED** [review]
Looks good, moving around the map once it's in view is a little strange since the screen keeps wanting to scroll instead of look around the map. I'd just put that on the issues list though.

**Review by ArthurMoreDonuts — APPROVED** [review]
Splendid, looks great.

**Review by DLabbate — APPROVED** [review]
Approved, but make sure to take care of the merge conflicts.

**Pull request merged**
