### PR TITLE
Workout ordering

### PR DESCRIPTION
**Pull request by BDeslippe23**
This branch added the ordering ability to the log fragment. It allows the user to order the workouts by date, distance, or duration. The tiles in the recycler view were modified slightly to show this information.

### CODE REVIEW

**Review by DLabbate — APPROVED** [review]
@BDeslippe23 Great work. It is functional as intended.

Only thing is the log fragment card view is cut off for me. 

Can you perhaps change the height to "wrap content" (see attached image). I can do this in a separate PR if it is preferrable.

image

**Comment by DLabbate** [comment]
@BDeslippe23 , I also noticed that if we are in the Fitness Fragment and move to the Map Fragment, a toast will display "ordered by Date". Should we remove the toast for now to avoid this?

**Review by glepore98 — APPROVED** [review]
Nice job

**Review by ArthurMoreDonuts — APPROVED** [review]
Apologies for the late response

**Pull request merged**
