### PR TITLE
Profile Activity

### PR DESCRIPTION
**Pull request by DLabbate**
- Added shared preference helper for profile info (name, age, weight (kg), gender)
- Navigates to profile activity if no information has been set yet
- Custom toolbar with profile icon if user wants to edit their info

### CODE REVIEW

**Review by ArthurMoreDonuts — APPROVED** [review]
Marvelous, it would be great if you can add some restriction to weight and age, since they accept zero as an input, and maybe we should have maximum weight.

**Review by BDeslippe23 — APPROVED** [review]
I am testing on a much smaller phone than the pixel, or the G4 (which gianluca has), so the biking icon and the profile icon are overlapping in the top right of the toolbar. I can still click to get to profile but it doesn't look pretty on this phone. Is this the same on the others

**Comment by ArthurMoreDonuts** [comment]
@BDeslippe23 It looks great on pixel. They do not overlap.

**Comment by DLabbate** [comment]
@BDeslippe23 , @ArthurMoreDonuts , I edited the toolbar margins could you test again? Also what phone are you using Brady?

**Review by boupat — APPROVED** [review]

**Review by glepore98 — APPROVED** [review]

**Pull request merged**
