### PR TITLE
Recording manager

### PR DESCRIPTION
**Pull request by DLabbate**
- Added foreground location service for updating speed and distance in the background
- Application can now receive HR data from Bluetooth sensor in background
- LogFragment data is no longer hardcoded. Added RecordingService to push workout data to DB

### CODE REVIEW

**Review by BDeslippe23 — APPROVED** [review]
Looks Good.

**Review by glepore98 — APPROVED** [review]

**Review by boupat — APPROVED** [review]

**Review by ArthurMoreDonuts — APPROVED** [review]
Splendid, I would like to point out that the app crashes after rotating the screen.

**Comment by DLabbate** [comment]
@ArthurMoreDonuts , thank you for pointing that out. I disabled landscape mode now. Can you test again please?

**Comment by ArthurMoreDonuts** [comment]
@DLabbate  I just checked, it is working fine,thanks.

**Pull request merged**
