### PR TITLE
Gps Feature

### PR DESCRIPTION
**Pull request by glepore98**
- User can see google map in GPS fragment 
- User can recenter on present location

### CODE REVIEW

**Comment by DLabbate** [comment]
@glepore98 , is there a way to inform the user that their location is disabled? Or give a toast for them to enable it? Because when the location is not enabled the map won't re-center. 

Other than that it is very good

**Comment by DLabbate** [comment]
@glepore98 Also would it be possible to merge the master branch into this one first?

**Comment by glepore98** [comment]
@DLabbate I will work on the location service request now. And ill try merging it

**Comment by glepore98** [comment]
@DLabbate should i merge only after i finish the location permissions? Since it might crash on my emulator because of the bluetooth

**Comment by DLabbate** [comment]
> @DLabbate should i merge only after i finish the location permissions? Since it might crash on my emulator because of the bluetooth

@glepore98 yea good point. Finish the location permissions first before any merging.

**Comment by DLabbate** [comment]
@glepore98 , make sure to resolve the conflicts before we merge this branch

**Pull request merged**
